<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mrshopapi.ps_accounts_facade' shared service.

return $this->services['mrshopapi.ps_accounts_facade'] = new \PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts(${($_ = isset($this->services['mrshopapi.ps_accounts_installer']) ? $this->services['mrshopapi.ps_accounts_installer'] : ($this->services['mrshopapi.ps_accounts_installer'] = new \PrestaShop\PsAccountsInstaller\Installer\Installer('5.0'))) && false ?: '_'});
