<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mrshopapi.ps_billings_facade' shared service.

return $this->services['mrshopapi.ps_billings_facade'] = new \PrestaShopCorp\Billing\Presenter\BillingPresenter(${($_ = isset($this->services['mrshopapi.ps_billings_context_wrapper']) ? $this->services['mrshopapi.ps_billings_context_wrapper'] : $this->load('getMrshopapi_PsBillingsContextWrapperService.php')) && false ?: '_'}, ${($_ = isset($this->services['mrshopapi.module']) ? $this->services['mrshopapi.module'] : $this->load('getMrshopapi_ModuleService.php')) && false ?: '_'});
