<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mrshopapi.ps_billings_context_wrapper' shared service.

return $this->services['mrshopapi.ps_billings_context_wrapper'] = new \PrestaShopCorp\Billing\Wrappers\BillingContextWrapper(${($_ = isset($this->services['mrshopapi.ps_accounts_facade']) ? $this->services['mrshopapi.ps_accounts_facade'] : $this->load('getMrshopapi_PsAccountsFacadeService.php')) && false ?: '_'}, ${($_ = isset($this->services['mrshopapi.context']) ? $this->services['mrshopapi.context'] : $this->load('getMrshopapi_ContextService.php')) && false ?: '_'}, false);
