<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mrshopapi.module' shared service.

return $this->services['mrshopapi.module'] = \Module::getInstanceByName('mrshopapi');
