<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQcw1j9l\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQcw1j9l/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQcw1j9l.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQcw1j9l\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQcw1j9l\appDevDebugProjectContainer([
    'container.build_hash' => 'Qcw1j9l',
    'container.build_id' => '6c4a90a0',
    'container.build_time' => 1705750918,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQcw1j9l');
